include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.gr.dart]
linter:
  rules:
    public_member_api_docs: false
    strict-raw-types: false
